### ISSUE TITLE
Maintenance and crate status

### ISSUE THREAD

**Issue by V0ldek** [Elzair/page_size_rs#8]
@Elzair 

A few major crates in the community (blake3, wasmer) depend on this crate. I heavily depend on this crate in my projects as well and would like to see it maintained, especially for WASM support (#5, #3, #2).

Seeing the last update at 3 years and the unresolved PR-s I think it's obvious this crate is no longer actively maintained.  I would volunteer to take over to avoid the project dying. Can we do something to get those PRs closed and move on?

**Comment by Elzair** [comment]
I will look into it.

**Comment by Elzair** [comment]
I am actually getting back into rust and will release a new version very soon.

**Comment by cryptoquick** [comment]
@Elzair How's that coming? Do you think you might need to add another maintainer?

**Comment by Elzair** [comment]
I just updated it.
